Script started on Fri Oct 23 18:02:50 2020

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
[?1034hbash-3.2$ gcc project1.c -o project1[C[C[C[C[C[C[C[C[C[C[K./prohect[K[K[K[Kject1 jeremy 10 10
Your username is jeremy. The row size is 10 and column size 10

Would you like to view the top scores? (y/n) y

How many top scores would you like to view? 3

jeremy had a score of 5000.00 in 0.0 seconds of play
jeremy had a score of 760.00 in 16.0 seconds of play
jeremy had a score of 125.00 in 2.0 seconds of play

Would you like to view the top scores? (y/n) y

How many top scores would you like to view? 5

jeremy had a score of 5000.00 in 0.0 seconds of play
jeremy had a score of 760.00 in 16.0 seconds of play
jeremy had a score of 125.00 in 2.0 seconds of play
jeremy had a score of 102.00 in 2.0 seconds of play
jeremy had a score of 91.00 in 13.0 seconds of play

Would you like to view the top scores? (y/n) n


 $ -3.62 -4.06 4.79 12.73 0.37 $ -8.50 -5.22 -6.66
 $ -0.21 $ -0.44 9.98 0.41 9.00 -0.42 1.75 1.09
 $ 7.19 10.51 6.65 -0.88 11.04 $ 14.50 -12.42 5.22
 -0.98 $ $ -13.99 13.77 7.99 0.44 -8.82 -4.28 -9.46
 $ 8.05 $ -0.58 -4.90 @ -3.19 10.77 6.42 #
 $ $ -6.12 -3.54 14.97 7.73 -0.59 11.20 8.12 3.51
 4.01 -13.54 $ * 1.34 -12.98 13.68 0.57 -4.60 14.48
 -7.05 -13.00 0.13 2.26 3.42 -10.48 -8.25 $ 14.33 -3.59
 $ 2.30 $ 13.26 -2.66 1.31 14.79 2.06 -5.04 -0.46
 -0.95 $ $ -4.52 10.24 -7.71 -6.98 2.00 -7.19 -0.90


Total negative numbers is 39/100 = 39.00 percent

X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 

Enter bomb position (x,y):5,7
Your input was 5,7

Total uncovered score of 42.38 points
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X - + + X 
X X X X X X - + + X 
X X X X X X + + - X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
Lives: 3
Score: 42.38
Bombs: 2
Enter bomb position (x,y):1,3
Your input was 1,3

Total uncovered score of 39.27 points
X X - + + X X X X X 
X X $ - + X X X X X 
X X + + - X X X X X 
X X X X X X X X X X 
X X X X X X - + + X 
X X X X X X - + + X 
X X X X X X + + - X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
Lives: 3
Score: 81.66
Bombs: 1
Enter bomb position (x,y):6,2 0
Your input was 6,0

Bang!! Your bomb range will be increased
Total uncovered score of -25.21 points

Your score has dipped below zero and therefore you've lost a life
X X - + + X X X X X 
X X $ - + X X X X X 
X X + + - X X X X X 
X X X X X X X X X X 
$ + $ X X X - + + X 
$ $ - X X X - + + X 
+ - $ X X X + + - X 
- - + X X X X X X X 
$ + $ X X X X X X X 
X X X X X X X X X X 
Lives: 1
Score: 0.00
Bombs: 0

Game over! Your name, score, and duration of play have been recorded.

Would you like to view the top scores? (y/n) y

How many top scores would you like to view? 6

jeremy had a score of 5000.00 in 0.0 seconds of play
jeremy had a score of 760.00 in 16.0 seconds of play
jeremy had a score of 125.00 in 2.0 seconds of play
jeremy had a score of 102.00 in 2.0 seconds of play
jeremy had a score of 91.00 in 13.0 seconds of play
jeremy had a score of 68.00 in 2.0 seconds of play

Would you like to view the top scores? (y/n) n


Program ended
bash-3.2$ exit
exit

Script done on Fri Oct 23 18:04:17 2020
